Feature/optimizer costmap2d tests
FastSense/local_planners pull request #2
Opened 2021-09-22 10:09 UTC by KostyaYamshanov

Добавил функциональный тест для MPPIC Optimizer.
Суть теста заключется в проверке траектории от optimizer на наличие коллизий с препятствиями на costmap.

Как собрать
`colcon build --packages-select mppic --cmake-args -DBUILD_TESTING=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON`

Как запустить
1. Или 
`colcon test --packages-select mppic`
2. Для дополнительного вывода
`colcon test --packages-select mppic --ctest-args -VV --event-handlers console_direct+`

2021-09-22 11:24 UTC, artofnothingness requested changes

2021-09-22 11:24 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +#include <cstddef>
Зачем этот заголовок?

2021-09-22 11:24 UTC, artofnothingness commented on mppic/test/tests_utils.hpp
> +/**
В плюсах докстринги перед сигнатурой функции

2021-09-22 11:24 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +printMapWthGoalAndTrajectory(*costmap_ros->getCostmap(), trajectory, ps);
нулевой отступ только для директив ifdef, остальное как обычный код

2021-09-22 11:24 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +  SECTION("Running evalTrajectoryFromControlSequence") {
Тут не только этот метод вызывается. Он только пропагейтит уже найденную последовательность управлений. 
Не понятно что тест проверяет по названию. Я бы назвал evalNextBestControl doesn't produce path crossing the obstacles". 
Так же такое большое количество итераций скорее всего не обяательно, тест сильно долго считается. Если подключить к этому бенчмарки, который много раз прогоняет тест, он просто ляжет.

2021-09-22 11:24 UTC, artofnothingness commented on mppic/test/tests_utils.hpp
> +void printMapWthGoalAndTrajectory(nav2_costmap_2d::Costmap2D & costmap, const auto & trajectory,
Опечатка

2021-09-22 11:24 UTC, artofnothingness commented on mppic/test/tests_utils.hpp
> +  for (auto i = trajectory.begin(); i < trajectory.end(); i+=3){
Тут я сначала не понял, а потом кажется понял) Ты итерируешься по всем эллементам и скипаешь длинну одного эллемента? Точно не стоит так делать) 
```
for (int i = 0; i < trajectory.shape()[0]; ++i) {
    trajectory(i, 0), trajectory(i, 1), trajectory(i,2); // (x, y, yaw)
}
```

2021-09-22 11:24 UTC, artofnothingness commented on mppic/test/tests_utils.hpp
> +  for (auto i = trajectory.begin(); i < trajectory.end(); i+=3){
итераторы обычно обзывают it. 
i это больше к индексам

2021-09-22 12:37 UTC, KostyaYamshanov commented on mppic/CMakeLists.txt
> +option(BUILD_TESTING "Build the testing tree." ON)
убрал, вроде работает и без. Добавлял, потому что так делали в примере от NAV2, в который я подглядывал

2021-09-22 12:38 UTC, KostyaYamshanov commented on mppic/CMakeLists.txt
> +if(BUILD_TESTING)
убрал выделение одной строкой, убрал опцию из Cmake в test

2021-09-22 12:38 UTC, KostyaYamshanov commented on mppic/test/CMakeLists.txt
> +  if(&{PRINT_COSTMAP})
опечатку убрал ) 
теперь там ${TEST_DEBUG_INFO}

2021-09-22 12:39 UTC, KostyaYamshanov commented on mppic/test/optimizer-test.cpp
> +#include <cstddef>
убрал

2021-09-22 12:39 UTC, KostyaYamshanov commented on mppic/test/tests_utils.hpp
> +/**
переместил, теперь они над сигнатурой

2021-09-22 12:39 UTC, KostyaYamshanov commented on mppic/test/optimizer-test.cpp
> +printMapWthGoalAndTrajectory(*costmap_ros->getCostmap(), trajectory, ps);
исправил отступы

2021-09-22 12:40 UTC, KostyaYamshanov commented on mppic/test/optimizer-test.cpp
> +  SECTION("Running evalTrajectoryFromControlSequence") {
переименовал, уменьшил количество итераций, тест должен стать полегковеснее

2021-09-22 12:40 UTC, KostyaYamshanov commented on mppic/test/tests_utils.hpp
> +void printMapWthGoalAndTrajectory(nav2_costmap_2d::Costmap2D & costmap, const auto & trajectory,
исправил

2021-09-22 12:41 UTC, KostyaYamshanov commented on mppic/test/tests_utils.hpp
> +  for (auto i = trajectory.begin(); i < trajectory.end(); i+=3){
переписал под твой пример, в принципе я его видел, но решил что с итераторами будет тоже не плохо )

2021-09-22 13:29 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +  SECTION("Running evalTrajectoryFromControlSequence") {
@KostyaYamshanov 50 все еще много. На реальном роботе сейчас максимум будет 5. Попробуй 2-5 итераций. Или он начинает врезаться?

2021-09-22 13:45 UTC, artofnothingness requested changes

2021-09-22 13:45 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +    std::string frame = "odom";                // frame for header in path
Старайся избегать комментариев, если можно заменить на более подробный нейминг.  Тут кстати фрейм не только для пути, но и для точек.

2021-09-22 13:45 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +    nav_msgs::msg::Path path;                  // reference path
Тоже самое. Назови переменную reference_path лучше.

2021-09-22 13:45 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +    geometry_msgs::msg::PoseStamped ps;        // goal point in reference path
reference_pose / reference_goal_pose

2021-09-22 13:45 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +    geometry_msgs::msg::Twist twist;           // initial robot velocity
robot_velocity / robot_speed.

Не подумай что я прикапываюсь. Я сам так переменные называю, но только когда считаю что нет смысла давать более подробное описание, а тут ты его даешь, а раз уж даешь, лучше неймингом, а не комментариями.

2021-09-22 13:45 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +    geometry_msgs::msg::PoseStamped init_cond; // initial robot pose
robot_pose

2021-09-22 13:45 UTC, artofnothingness commented on mppic/test/tests_utils.hpp
> +void setUpOptimizerParams(std::vector<rclcpp::Parameter> &params_){
Эта штуку лучше убрать из test_utils, она не слишком то генерализована для разных тестов. Она скорее подходит для одного тест кейса - твоего. Думаю ее прям в сам тест лучше.

2021-09-22 16:08 UTC, KostyaYamshanov commented on mppic/test/optimizer-test.cpp
> +  SECTION("Running evalTrajectoryFromControlSequence") {
@artofnothingness  Путь получается в 2-4 клетки на костмапе, ну в принципе этого хватает, чтобы понять что все окей

2021-09-22 16:11 UTC, KostyaYamshanov commented
Поправил нейминг, убрал лишние комменты
Сразу не увидел коммент про iteration_count, поствил этот параметр поменьше (=5), и сместил препятствие немного, ну в приницпе можно понять что все окей

2021-09-22 16:54 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +  SECTION("Running evalTrajectoryFromControlSequence") {
@KostyaYamshanov А.. Он разойтись не успевает. Тогда можно чуть побольше. Но желательно поменьше.

2021-09-22 17:06 UTC, merged

2021-09-23 09:59 UTC, urock commented
а как задавалась costmap?

2021-09-23 10:05 UTC, artofnothingness commented
@urock Создавался Costmap2D и у него есть метод setCost, в котором указывается ячейка и значение. Далее этот костмап передавался в MPPI.

2021-09-23 10:07 UTC, urock commented
а вижу, как
![image](https://user-images.githubusercontent.com/1125366/134489035-e21e2471-ad29-4faf-95e7-a0beb80382c5.png)

на будующее можно подумать о более высокоуровневых тестах но все еще без газебо:

запускаем несколько нод и тикает время, нода контроллера получается позу, костмап и дает контрол, этот контрол другим модулем принимается и обновляет позу, цикл повторяется. 

костмап при этом можно из файла задавать, например просто картинкой, которую можно самому отредактировать

2021-09-23 10:08 UTC, urock commented
норм, молодцы, все хорошо!