Feature/grid map tests
FastSense/local_planners pull request #3
Opened 2021-09-27 10:01 UTC by KostyaYamshanov

Добавил 4 теста на гридмап
когда есть непроходимое препятствие
![image](https://user-images.githubusercontent.com/38326063/134900713-d0497872-c448-41e0-b121-92392cb44e0f.png)

когда есть проходимый холмик
![image](https://user-images.githubusercontent.com/38326063/134900780-df15d263-071b-4fb8-89aa-7d0f1b6c1515.png)

Спуск с холмика
![image](https://user-images.githubusercontent.com/38326063/134900821-7da83573-6d7f-45f5-b49a-d6a1df9d27dc.png)

Когда ничего не мешает
![image](https://user-images.githubusercontent.com/38326063/134900840-99723966-a873-42a3-8597-f21547519c92.png)

2021-09-27 13:09 UTC, KostyaYamshanov commented
Увеличил количество итераций, теперь траектория подлиннее
![image](https://user-images.githubusercontent.com/38326063/134914712-6d8f316d-ec74-460f-aedd-6d117d0a8625.png)

2021-09-27 14:38 UTC, artofnothingness requested changes

2021-09-27 14:38 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +#include <cstdio>
наверное лишнее

2021-09-27 14:38 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +  printf("GridMap \n start point=-100 trajectory=-1 goal point=100 \n");
Почему не cout

2021-09-27 14:38 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +void makeFlatGridMapLayer(grid_map::GridMap & grid_map, std::string & layer_name){
Вроде есть метод setZero() у grid_map['layer_name'].
Ну и нейминг. В комментарии fills , а в названии make. Кстати в комментариях обычно нужно писать Fill, без 's'. Короче в другом времени пишется обычно

2021-09-27 14:38 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +                          const int & cx, const int & cy){
grid_map::Index вместо cx, cy, и назвать как-то понятно типа upper_left_corner

2021-09-27 14:38 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +  int cx_ = cx;
нейминг

2021-09-27 14:38 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +  int cx_ = cx;
А зачем вообще создавать эту переменную ? Почему cx не использовать?

2021-09-27 14:38 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +  int cx_ = cx;
А. Понял. Короче все легкие переменные double, int, float передавай по значению, чтобы копировалось

2021-09-27 14:38 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +  int cx_ = cx;
Тоже самое Index можно скопировать, там 2 значения

2021-09-27 14:38 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +                         const int & cx, const int & cy){
тоже самое. Всей флоаты, инты копировать проще

2021-09-27 14:38 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +    // float start_point_x = 1.25;
Это нужно?

2021-09-27 14:38 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +  // int obstacle_step_k = GENERATE(1);
Это нужно?

2021-09-27 14:38 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +          // std::cout<<reference_goal_pose.pose.position.x<< " "<<reference_goal_pose.pose.position.y<<std::endl;
Это нужно?

2021-09-27 14:38 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +    bool result = checkTrajectoryCollision(*grid_map, layer_name, robot_clearance, trajectory);
Может лучше назвать `inCollision` метод. Тогда 
`CHECK(!InCollison(...));` Звучит логичнее, понятно что он столкнулся или нет, а не прочекал или нет
`CHECK` тут чтобы при фейле дальше тест кейс исполнялся и принтанул если стоит флаг
```
if (TEST_DEBUG_INFO) {
    printSmthing
}
```

2021-09-27 14:38 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +      printGridMapLayerWithTrajectoryAndGoal(*grid_map, layer_name, trajectory, reference_goal_pose);
Мы вроде принтим если у нас флаг компилятора установлен.
```
if (TEST_DEBUG_INFO) {
    printSmthing
}
```

2021-09-27 18:44 UTC, KostyaYamshanov commented on mppic/test/optimizer-test.cpp
> +      printGridMapLayerWithTrajectoryAndGoal(*grid_map, layer_name, trajectory, reference_goal_pose);
добавил флаг в Cmake, изменил условие вывода

2021-09-27 18:44 UTC, KostyaYamshanov commented on mppic/test/optimizer-test.cpp
> +    bool result = checkTrajectoryCollision(*grid_map, layer_name, robot_clearance, trajectory);
переименовал метод

2021-09-27 18:44 UTC, KostyaYamshanov commented on mppic/test/optimizer-test.cpp
> +          // std::cout<<reference_goal_pose.pose.position.x<< " "<<reference_goal_pose.pose.position.y<<std::endl;
убрал лишние комменты

2021-09-27 18:44 UTC, KostyaYamshanov commented on mppic/test/optimizer-test.cpp
> +  // int obstacle_step_k = GENERATE(1);
убрал лишние комменты

2021-09-27 18:44 UTC, KostyaYamshanov commented on mppic/test/optimizer-test.cpp
> +    // float start_point_x = 1.25;
убрал лишние комменты

2021-09-27 18:44 UTC, KostyaYamshanov commented on mppic/test/optimizer-test.cpp
> +                         const int & cx, const int & cy){
пофиксил

2021-09-27 18:44 UTC, KostyaYamshanov commented on mppic/test/optimizer-test.cpp
> +  int cx_ = cx;
пофиксил

2021-09-27 18:44 UTC, KostyaYamshanov commented on mppic/test/optimizer-test.cpp
> +                          const int & cx, const int & cy){
переименовал

2021-09-27 18:45 UTC, KostyaYamshanov commented on mppic/test/optimizer-test.cpp
> +void makeFlatGridMapLayer(grid_map::GridMap & grid_map, std::string & layer_name){
убрал этот метод, просто использую метод setZero (чет забыл про него хотя видел)

2021-09-27 18:45 UTC, KostyaYamshanov commented on mppic/test/optimizer-test.cpp
> +  printf("GridMap \n start point=-100 trajectory=-1 goal point=100 \n");
для единообразия сделал cout

2021-09-27 18:45 UTC, KostyaYamshanov commented on mppic/test/optimizer-test.cpp
> +#include <cstdio>
убрал

2021-09-28 08:20 UTC, artofnothingness requested changes

2021-09-28 08:20 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +                          int upper_left_corner_x, int upper_left_corner_y){
используй grid_map::Index, вместо пары x, y

2021-09-28 08:20 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +                         int  upper_left_corner_x, int upper_left_corner_y){
Тоже самое

2021-09-28 08:20 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +                              const float & robot_clearance,
Передавай по значению

2021-09-28 08:20 UTC, artofnothingness commented on mppic/test/optimizer-test.cpp
> +  // std::cout<<robot_clearance<<std::endl;
Это как опция принта ? Если да, то ок, но вообще лучше все обернуть в TEST_DEBUG_INFO

2021-09-28 10:04 UTC, merged